// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	ServiceName string
	Price       int32
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}
