// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const allSubscriptions = `-- name: AllSubscriptions :many
SELECT id, user_id, service_name, price, start_date, end_date
FROM subscriptions
LIMIT $1::INT OFFSET $1::INT * $2::INT
`

type AllSubscriptionsParams struct {
	Count int32
	Page  int32
}

func (q *Queries) AllSubscriptions(ctx context.Context, arg AllSubscriptionsParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, allSubscriptions, arg.Count, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceName,
			&i.Price,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, service_name, price, start_date, end_date)
VALUES ($1::uuid, $2::TEXT, $3::INT, $4::DATE,
        $5::DATE)
RETURNING id, user_id, service_name, price, start_date, end_date
`

type CreateSubscriptionParams struct {
	UserID      pgtype.UUID
	ServiceName string
	Price       int32
	StartDate   pgtype.Date
	EndDate     pgtype.Date
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE
FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, subscriptionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, subscriptionID)
	return err
}

const getSubscriptionById = `-- name: GetSubscriptionById :one
SELECT id, user_id, service_name, price, start_date, end_date
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscriptionById(ctx context.Context, subscriptionID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionById, subscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const getSumSubscriptions = `-- name: GetSumSubscriptions :one
SELECT COALESCE(SUM(price * (
    (EXTRACT (YEAR FROM (LEAST(COALESCE(end_date, $1::DATE), $1::DATE))) -
     EXTRACT (YEAR FROM GREATEST(start_date, $2::DATE))) * 12 +
    (EXTRACT (MONTH FROM (LEAST(COALESCE(end_date, $1::DATE), $1::DATE))) -
     EXTRACT (MONTH FROM GREATEST(start_date, $2::DATE))) + 1
    )), 0)::INT
FROM subscriptions
WHERE start_date <= $1::DATE
  AND (end_date IS NULL OR end_date >= $2::DATE)
  AND ($3::TEXT IS NULL OR service_name ILIKE $3::TEXT)
  AND ($4::uuid IS NULL OR user_id = $4::uuid)
`

type GetSumSubscriptionsParams struct {
	EndDate     pgtype.Date
	StartDate   pgtype.Date
	ServiceName pgtype.Text
	UserID      pgtype.UUID
}

func (q *Queries) GetSumSubscriptions(ctx context.Context, arg GetSumSubscriptionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, getSumSubscriptions,
		arg.EndDate,
		arg.StartDate,
		arg.ServiceName,
		arg.UserID,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET user_id      = COALESCE($1::uuid, user_id),
    service_name = COALESCE($2::TEXT, service_name),
    price        = COALESCE($3::INT, price),
    start_date   = COALESCE($4::DATE, start_date),
    end_date     = COALESCE($5::DATE, end_date)
WHERE id = $6
RETURNING id, user_id, service_name, price, start_date, end_date
`

type UpdateSubscriptionParams struct {
	UserID         pgtype.UUID
	ServiceName    pgtype.Text
	Price          pgtype.Int4
	StartDate      pgtype.Date
	EndDate        pgtype.Date
	SubscriptionID pgtype.UUID
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.UserID,
		arg.ServiceName,
		arg.Price,
		arg.StartDate,
		arg.EndDate,
		arg.SubscriptionID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceName,
		&i.Price,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
