// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/subscriptions.proto

package api

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *string                `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionRequest) Reset() {
	*x = AddSubscriptionRequest{}
	mi := &file_api_subscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionRequest) ProtoMessage() {}

func (x *AddSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*AddSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *AddSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddSubscriptionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AddSubscriptionRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AddSubscriptionRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *AddSubscriptionRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

type AddSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddSubscriptionResponse) Reset() {
	*x = AddSubscriptionResponse{}
	mi := &file_api_subscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSubscriptionResponse) ProtoMessage() {}

func (x *AddSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*AddSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *AddSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type GetSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetSubscriptionRequest) Reset() {
	*x = GetSubscriptionRequest{}
	mi := &file_api_subscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionRequest) ProtoMessage() {}

func (x *GetSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *GetSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type GetSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionResponse) Reset() {
	*x = GetSubscriptionResponse{}
	mi := &file_api_subscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionResponse) ProtoMessage() {}

func (x *GetSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *GetSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type GetSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *int32                 `protobuf:"varint,1,opt,name=count,proto3,oneof" json:"count,omitempty"`
	Page          *int32                 `protobuf:"varint,2,opt,name=page,proto3,oneof" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsRequest) Reset() {
	*x = GetSubscriptionsRequest{}
	mi := &file_api_subscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsRequest) ProtoMessage() {}

func (x *GetSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{4}
}

func (x *GetSubscriptionsRequest) GetCount() int32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *GetSubscriptionsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

type GetSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*Subscription        `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionsResponse) Reset() {
	*x = GetSubscriptionsResponse{}
	mi := &file_api_subscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionsResponse) ProtoMessage() {}

func (x *GetSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *GetSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type UpdateSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	UserId         *string                `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	ServiceName    *string                `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3,oneof" json:"service_name,omitempty"`
	Price          *int32                 `protobuf:"varint,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	StartDate      *string                `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3,oneof" json:"start_date,omitempty"`
	EndDate        *string                `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_api_subscriptions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetPrice() int32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateSubscriptionRequest) GetStartDate() string {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return ""
}

func (x *UpdateSubscriptionRequest) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

type UpdateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionResponse) Reset() {
	*x = UpdateSubscriptionResponse{}
	mi := &file_api_subscriptions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionResponse) ProtoMessage() {}

func (x *UpdateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type DeleteSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteSubscriptionRequest) Reset() {
	*x = DeleteSubscriptionRequest{}
	mi := &file_api_subscriptions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionRequest) ProtoMessage() {}

func (x *DeleteSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type DeleteSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubscriptionResponse) Reset() {
	*x = DeleteSubscriptionResponse{}
	mi := &file_api_subscriptions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubscriptionResponse) ProtoMessage() {}

func (x *DeleteSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{9}
}

type GetSumSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	UserId        *string                `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	ServiceName   *string                `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3,oneof" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSumSubscriptionsRequest) Reset() {
	*x = GetSumSubscriptionsRequest{}
	mi := &file_api_subscriptions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSumSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSumSubscriptionsRequest) ProtoMessage() {}

func (x *GetSumSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSumSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*GetSumSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{10}
}

func (x *GetSumSubscriptionsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *GetSumSubscriptionsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *GetSumSubscriptionsRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *GetSumSubscriptionsRequest) GetServiceName() string {
	if x != nil && x.ServiceName != nil {
		return *x.ServiceName
	}
	return ""
}

type GetSumSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSum      int32                  `protobuf:"varint,1,opt,name=total_sum,json=totalSum,proto3" json:"total_sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSumSubscriptionsResponse) Reset() {
	*x = GetSumSubscriptionsResponse{}
	mi := &file_api_subscriptions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSumSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSumSubscriptionsResponse) ProtoMessage() {}

func (x *GetSumSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSumSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*GetSumSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{11}
}

func (x *GetSumSubscriptionsResponse) GetTotalSum() int32 {
	if x != nil {
		return x.TotalSum
	}
	return 0
}

type Subscription struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServiceName    string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Price          int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	StartDate      string                 `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        *string                `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3,oneof" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_api_subscriptions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_subscriptions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_api_subscriptions_proto_rawDescGZIP(), []int{12}
}

func (x *Subscription) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Subscription) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Subscription) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Subscription) GetEndDate() string {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return ""
}

var File_api_subscriptions_proto protoreflect.FileDescriptor

const file_api_subscriptions_proto_rawDesc = "" +
	"\n" +
	"\x17api/subscriptions.proto\x12\x03api\x1a\x1cgoogle/api/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xf6\x03\n" +
	"\x16AddSubscriptionRequest\x12D\n" +
	"\auser_id\x18\x01 \x01(\tB+\x92A\x1d*\x1bID пользователя\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x06userId\x12[\n" +
	"\fservice_name\x18\x02 \x01(\tB8\x92A+*)Наименование подписки\xbaH\a\xc8\x01\x01r\x02\x10\x03R\vserviceName\x12H\n" +
	"\x05price\x18\x03 \x01(\x05B2\x92A%*#Стоимость подписки\xbaH\a\xc8\x01\x01\x1a\x02(\x00R\x05price\x12n\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tBO\x92A(*&Дата старта подписки\xbaH!\xc8\x01\x01r\x1c2\x1a^(1[0-2]|0[1-9])-[0-9]{4}$R\tstartDate\x12r\n" +
	"\bend_date\x18\x05 \x01(\tBR\x92A.*,Дата окончания подписки\xbaH\x1er\x1c2\x1a^(1[0-2]|0[1-9])-[0-9]{4}$H\x00R\aendDate\x88\x01\x01B\v\n" +
	"\t_end_date\"P\n" +
	"\x17AddSubscriptionResponse\x125\n" +
	"\fsubscription\x18\x01 \x01(\v2\x11.api.SubscriptionR\fsubscription\"f\n" +
	"\x16GetSubscriptionRequest\x12L\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tB#\x92A\x15*\x13ID подписки\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0esubscriptionId\"P\n" +
	"\x17GetSubscriptionResponse\x125\n" +
	"\fsubscription\x18\x01 \x01(\v2\x11.api.SubscriptionR\fsubscription\"\xd2\x01\n" +
	"\x17GetSubscriptionsRequest\x12b\n" +
	"\x05count\x18\x01 \x01(\x05BG\x92A=*;Количество подписок на страницу\xbaH\x04\x1a\x02 \x00H\x00R\x05count\x88\x01\x01\x12@\n" +
	"\x04page\x18\x02 \x01(\x05B'\x92A\x1d*\x1bНомер страницы\xbaH\x04\x1a\x02 \x00H\x01R\x04page\x88\x01\x01B\b\n" +
	"\x06_countB\a\n" +
	"\x05_page\"S\n" +
	"\x18GetSubscriptionsResponse\x127\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x11.api.SubscriptionR\rsubscriptions\"\x85\x05\n" +
	"\x19UpdateSubscriptionRequest\x12L\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tB#\x92A\x15*\x13ID подписки\xbaH\b\xc8\x01\x01r\x03\xb0\x01\x01R\x0esubscriptionId\x12F\n" +
	"\auser_id\x18\x02 \x01(\tB(\x92A\x1d*\x1bID пользователя\xbaH\x05r\x03\xb0\x01\x01H\x00R\x06userId\x88\x01\x01\x12]\n" +
	"\fservice_name\x18\x03 \x01(\tB5\x92A+*)Наименование подписки\xbaH\x04r\x02\x10\x03H\x01R\vserviceName\x88\x01\x01\x12J\n" +
	"\x05price\x18\x04 \x01(\x05B/\x92A%*#Стоимость подписки\xbaH\x04\x1a\x02(\x00H\x02R\x05price\x88\x01\x01\x12p\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tBL\x92A(*&Дата старта подписки\xbaH\x1er\x1c2\x1a^(1[0-2]|0[1-9])-[0-9]{4}$H\x03R\tstartDate\x88\x01\x01\x12r\n" +
	"\bend_date\x18\x06 \x01(\tBR\x92A.*,Дата окончания подписки\xbaH\x1er\x1c2\x1a^(1[0-2]|0[1-9])-[0-9]{4}$H\x04R\aendDate\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\x0f\n" +
	"\r_service_nameB\b\n" +
	"\x06_priceB\r\n" +
	"\v_start_dateB\v\n" +
	"\t_end_date\"S\n" +
	"\x1aUpdateSubscriptionResponse\x125\n" +
	"\fsubscription\x18\x01 \x01(\v2\x11.api.SubscriptionR\fsubscription\"d\n" +
	"\x19DeleteSubscriptionRequest\x12G\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tB\x1e\x92A\x15*\x13ID подписки\xbaH\x03\xc8\x01\x01R\x0esubscriptionId\"\x1c\n" +
	"\x1aDeleteSubscriptionResponse\"\xc2\x03\n" +
	"\x1aGetSumSubscriptionsRequest\x12n\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tBO\x92A(*&Дата старта подписки\xbaH!\xc8\x01\x01r\x1c2\x1a^(1[0-2]|0[1-9])-[0-9]{4}$R\tstartDate\x12p\n" +
	"\bend_date\x18\x02 \x01(\tBU\x92A.*,Дата окончания подписки\xbaH!\xc8\x01\x01r\x1c2\x1a^(1[0-2]|0[1-9])-[0-9]{4}$R\aendDate\x12F\n" +
	"\auser_id\x18\x03 \x01(\tB(\x92A\x1d*\x1bID пользователя\xbaH\x05r\x03\xb0\x01\x01H\x00R\x06userId\x88\x01\x01\x12]\n" +
	"\fservice_name\x18\x04 \x01(\tB5\x92A+*)Наименование подписки\xbaH\x04r\x02\x10\x03H\x01R\vserviceName\x88\x01\x01B\n" +
	"\n" +
	"\b_user_idB\x0f\n" +
	"\r_service_name\"m\n" +
	"\x1bGetSumSubscriptionsResponse\x12N\n" +
	"\ttotal_sum\x18\x01 \x01(\x05B1\x92A.*,Итоговая сумма подписокR\btotalSum\"\xcb\x03\n" +
	"\fSubscription\x12A\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tB\x18\x92A\x15*\x13ID подпискиR\x0esubscriptionId\x129\n" +
	"\auser_id\x18\x02 \x01(\tB \x92A\x1d*\x1bID пользователяR\x06userId\x12Q\n" +
	"\fservice_name\x18\x03 \x01(\tB.\x92A+*)Наименование подпискиR\vserviceName\x12>\n" +
	"\x05price\x18\x04 \x01(\x05B(\x92A%*#Стоимость подпискиR\x05price\x12J\n" +
	"\n" +
	"start_date\x18\x05 \x01(\tB+\x92A(*&Дата старта подпискиR\tstartDate\x12Q\n" +
	"\bend_date\x18\x06 \x01(\tB1\x92A.*,Дата окончания подпискиH\x00R\aendDate\x88\x01\x01B\v\n" +
	"\t_end_date2\x8d\t\n" +
	"\rSubscriptions\x12\x94\x01\n" +
	"\x0fAddSubscription\x12\x1b.api.AddSubscriptionRequest\x1a\x1c.api.AddSubscriptionResponse\"F\x92A#\x12!Добавить подписку\x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/subscriptions\x12\xb0\x01\n" +
	"\x0fGetSubscription\x12\x1b.api.GetSubscriptionRequest\x1a\x1c.api.GetSubscriptionResponse\"b\x92A0\x12.Получить подписку по её ID\x82\xd3\xe4\x93\x02)\x12'/api/v1/subscriptions/{subscription_id}\x12\x9b\x01\n" +
	"\x10GetSubscriptions\x12\x1c.api.GetSubscriptionsRequest\x1a\x1d.api.GetSubscriptionsResponse\"J\x92A*\x12(Получить все подписки\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/subscriptions\x12\xaf\x01\n" +
	"\x12UpdateSubscription\x12\x1e.api.UpdateSubscriptionRequest\x1a\x1f.api.UpdateSubscriptionResponse\"X\x92A#\x12!Обновить подписку\x82\xd3\xe4\x93\x02,:\x01*\x1a'/api/v1/subscriptions/{subscription_id}\x12\xaa\x01\n" +
	"\x12DeleteSubscription\x12\x1e.api.DeleteSubscriptionRequest\x1a\x1f.api.DeleteSubscriptionResponse\"S\x92A!\x12\x1fУдалить подписку\x82\xd3\xe4\x93\x02)*'/api/v1/subscriptions/{subscription_id}\x12\xb4\x02\n" +
	"\x13GetSumSubscriptions\x12\x1f.api.GetSumSubscriptionsRequest\x1a .api.GetSumSubscriptionsResponse\"\xd9\x01\x92A\xb4\x01\x12\xb1\x01Получить сумму подписок за выбранный период с фильтрацией по ID пользователя и названию подписки\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/subscriptions/sumB\xd5\x01\x92A\xa1\x01\x12\x9e\x01\n" +
	"\x1dСервис подписок\x12xREST-сервис для агрегации данных об онлайн-подписках пользователей2\x031.0Z.github.com/Geriler/effective-mobile/pb/api;apib\x06proto3"

var (
	file_api_subscriptions_proto_rawDescOnce sync.Once
	file_api_subscriptions_proto_rawDescData []byte
)

func file_api_subscriptions_proto_rawDescGZIP() []byte {
	file_api_subscriptions_proto_rawDescOnce.Do(func() {
		file_api_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_subscriptions_proto_rawDesc), len(file_api_subscriptions_proto_rawDesc)))
	})
	return file_api_subscriptions_proto_rawDescData
}

var file_api_subscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_subscriptions_proto_goTypes = []any{
	(*AddSubscriptionRequest)(nil),      // 0: api.AddSubscriptionRequest
	(*AddSubscriptionResponse)(nil),     // 1: api.AddSubscriptionResponse
	(*GetSubscriptionRequest)(nil),      // 2: api.GetSubscriptionRequest
	(*GetSubscriptionResponse)(nil),     // 3: api.GetSubscriptionResponse
	(*GetSubscriptionsRequest)(nil),     // 4: api.GetSubscriptionsRequest
	(*GetSubscriptionsResponse)(nil),    // 5: api.GetSubscriptionsResponse
	(*UpdateSubscriptionRequest)(nil),   // 6: api.UpdateSubscriptionRequest
	(*UpdateSubscriptionResponse)(nil),  // 7: api.UpdateSubscriptionResponse
	(*DeleteSubscriptionRequest)(nil),   // 8: api.DeleteSubscriptionRequest
	(*DeleteSubscriptionResponse)(nil),  // 9: api.DeleteSubscriptionResponse
	(*GetSumSubscriptionsRequest)(nil),  // 10: api.GetSumSubscriptionsRequest
	(*GetSumSubscriptionsResponse)(nil), // 11: api.GetSumSubscriptionsResponse
	(*Subscription)(nil),                // 12: api.Subscription
}
var file_api_subscriptions_proto_depIdxs = []int32{
	12, // 0: api.AddSubscriptionResponse.subscription:type_name -> api.Subscription
	12, // 1: api.GetSubscriptionResponse.subscription:type_name -> api.Subscription
	12, // 2: api.GetSubscriptionsResponse.subscriptions:type_name -> api.Subscription
	12, // 3: api.UpdateSubscriptionResponse.subscription:type_name -> api.Subscription
	0,  // 4: api.Subscriptions.AddSubscription:input_type -> api.AddSubscriptionRequest
	2,  // 5: api.Subscriptions.GetSubscription:input_type -> api.GetSubscriptionRequest
	4,  // 6: api.Subscriptions.GetSubscriptions:input_type -> api.GetSubscriptionsRequest
	6,  // 7: api.Subscriptions.UpdateSubscription:input_type -> api.UpdateSubscriptionRequest
	8,  // 8: api.Subscriptions.DeleteSubscription:input_type -> api.DeleteSubscriptionRequest
	10, // 9: api.Subscriptions.GetSumSubscriptions:input_type -> api.GetSumSubscriptionsRequest
	1,  // 10: api.Subscriptions.AddSubscription:output_type -> api.AddSubscriptionResponse
	3,  // 11: api.Subscriptions.GetSubscription:output_type -> api.GetSubscriptionResponse
	5,  // 12: api.Subscriptions.GetSubscriptions:output_type -> api.GetSubscriptionsResponse
	7,  // 13: api.Subscriptions.UpdateSubscription:output_type -> api.UpdateSubscriptionResponse
	9,  // 14: api.Subscriptions.DeleteSubscription:output_type -> api.DeleteSubscriptionResponse
	11, // 15: api.Subscriptions.GetSumSubscriptions:output_type -> api.GetSumSubscriptionsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_subscriptions_proto_init() }
func file_api_subscriptions_proto_init() {
	if File_api_subscriptions_proto != nil {
		return
	}
	file_api_subscriptions_proto_msgTypes[0].OneofWrappers = []any{}
	file_api_subscriptions_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_subscriptions_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_subscriptions_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_subscriptions_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_subscriptions_proto_rawDesc), len(file_api_subscriptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_subscriptions_proto_goTypes,
		DependencyIndexes: file_api_subscriptions_proto_depIdxs,
		MessageInfos:      file_api_subscriptions_proto_msgTypes,
	}.Build()
	File_api_subscriptions_proto = out.File
	file_api_subscriptions_proto_goTypes = nil
	file_api_subscriptions_proto_depIdxs = nil
}
